services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8000:8000"  # For remote debugging
    depends_on:
      - db
      - minio
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}

  db:
    image: 'postgres:16.6'
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '5445:5445'
    command: [ "postgres", "-p", "5445" ]
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  minio:
    image: quay.io/minio/minio:RELEASE.2025-02-03T21-03-04Z
    command: server --console-address ":9001" /mnt/data
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/mnt/data
      - minio_config:/etc/config.env

volumes:
  minio_data:
  minio_config:
  postgres_data: