# Generated by Django 5.2.1 on 2025-05-12 09:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_specialization_client_master'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+375 (29) XXX-XX-XX'", regex='^\\+375 \\((?:29|33|44|25)\\) \\d{3}-\\d{2}-\\d{2}$')]),
        ),
        migrations.AlterField(
            model_name='master',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+375 (29) XXX-XX-XX'", regex='^\\+375 \\((?:29|33|44|25)\\) \\d{3}-\\d{2}-\\d{2}$')]),
        ),
    ]
