# Generated by Django 5.2.1 on 2025-05-12 09:55

import shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_client_address_alter_client_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='birth_date',
            field=models.DateField(validators=[shop.models.validate_18_years_or_older]),
        ),
        migrations.AlterField(
            model_name='master',
            name='birth_date',
            field=models.DateField(validators=[shop.models.validate_18_years_or_older]),
        ),
    ]
