# Generated by Django 5.2.1 on 2025-05-15 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_vacancy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Код промокода')),
                ('discount_type', models.CharField(choices=[('percentage', 'Процент'), ('fixed', 'Фиксированная сумма')], default='percentage', max_length=10, verbose_name='Тип скидки')),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Размер скидки')),
                ('valid_from', models.DateField(verbose_name='Действует с')),
                ('valid_to', models.DateField(verbose_name='Действует до')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('specializations', models.ManyToManyField(related_name='promocodes', to='shop.specialization', verbose_name='Специализации')),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокоды',
                'ordering': ['-valid_to'],
            },
        ),
    ]
